CREATE EXTENSION IF NOT EXISTS "pgcrypto";
DO $$ BEGIN CREATE TYPE "role" AS ENUM ('admin', 'user'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "client_type" AS ENUM ('store', 'company', 'individual'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "sale_status" AS ENUM ('completed', 'cancelled'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "shipping_type" AS ENUM ('none', 'internal', 'external'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE TABLE IF NOT EXISTS "users" ( "id" serial PRIMARY KEY NOT NULL, "username" text NOT NULL, "name" text NOT NULL, "password_hash" text NOT NULL, "role" "role" DEFAULT 'user' NOT NULL, "created_at" timestamp with time zone DEFAULT now() NOT NULL, CONSTRAINT "users_username_unique" UNIQUE("username") );
CREATE TABLE IF NOT EXISTS "sessions" ( "id" text PRIMARY KEY NOT NULL, "user_id" integer NOT NULL, "expires_at" timestamp with time zone NOT NULL, "created_at" timestamp with time zone DEFAULT now() NOT NULL );
DO $$ BEGIN ALTER TABLE "sessions" ADD CONSTRAINT "sessions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE cascade; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS "sessions_user_idx" ON "sessions" ("user_id");
CREATE TABLE IF NOT EXISTS "products" ( "id" serial PRIMARY KEY NOT NULL, "name" text NOT NULL, "category" text DEFAULT '' NOT NULL, "description" text DEFAULT '' NOT NULL, "price" numeric(12, 2) DEFAULT '0' NOT NULL, "cost" numeric(12, 2) DEFAULT '0' NOT NULL, "stock" integer DEFAULT 0 NOT NULL, "low_stock_at" integer DEFAULT 5 NOT NULL, "image_url" text DEFAULT '' NOT NULL, "archived" boolean DEFAULT false NOT NULL, "created_at" timestamp with time zone DEFAULT now() NOT NULL, "updated_at" timestamp with time zone DEFAULT now() NOT NULL );
CREATE INDEX IF NOT EXISTS "products_name_idx" ON "products" ("name");
CREATE TABLE IF NOT EXISTS "product_fields" ( "id" serial PRIMARY KEY NOT NULL, "product_id" integer NOT NULL, "label" text NOT NULL, "value" text NOT NULL );
DO $$ BEGIN ALTER TABLE "product_fields" ADD CONSTRAINT "product_fields_product_id_products_id_fk" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE cascade; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS "product_fields_product_idx" ON "product_fields" ("product_id");
CREATE TABLE IF NOT EXISTS "clients" ( "id" serial PRIMARY KEY NOT NULL, "name" text NOT NULL, "type" "client_type" DEFAULT 'individual' NOT NULL, "phone" text DEFAULT '' NOT NULL, "address" text DEFAULT '' NOT NULL, "notes" text DEFAULT '' NOT NULL, "created_at" timestamp with time zone DEFAULT now() NOT NULL );
CREATE INDEX IF NOT EXISTS "clients_name_idx" ON "clients" ("name");
CREATE TABLE IF NOT EXISTS "sales" ( "id" serial PRIMARY KEY NOT NULL, "client_id" integer NOT NULL, "user_id" integer NOT NULL, "status" "sale_status" DEFAULT 'completed' NOT NULL, "subtotal" numeric(12, 2) DEFAULT '0' NOT NULL, "shipping_type" "shipping_type" DEFAULT 'none' NOT NULL, "shipping_cost" numeric(12, 2) DEFAULT '0' NOT NULL, "total" numeric(12, 2) DEFAULT '0' NOT NULL, "profit" numeric(12, 2) DEFAULT '0' NOT NULL, "currency" text DEFAULT 'JOD' NOT NULL, "rate" numeric(14, 6) DEFAULT '1' NOT NULL, "notes" text DEFAULT '' NOT NULL, "created_at" timestamp with time zone DEFAULT now() NOT NULL );
DO $$ BEGIN ALTER TABLE "sales" ADD CONSTRAINT "sales_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "clients"("id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "sales" ADD CONSTRAINT "sales_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "users"("id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS "sales_created_idx" ON "sales" ("created_at");
CREATE INDEX IF NOT EXISTS "sales_client_idx" ON "sales" ("client_id");
CREATE TABLE IF NOT EXISTS "sale_items" ( "id" serial PRIMARY KEY NOT NULL, "sale_id" integer NOT NULL, "product_id" integer NOT NULL, "product_name" text NOT NULL, "image_url" text DEFAULT '' NOT NULL, "price" numeric(12, 2) NOT NULL, "cost" numeric(12, 2) DEFAULT '0' NOT NULL, "quantity" integer NOT NULL, "line_total" numeric(12, 2) NOT NULL );
DO $$ BEGIN ALTER TABLE "sale_items" ADD CONSTRAINT "sale_items_sale_id_sales_id_fk" FOREIGN KEY ("sale_id") REFERENCES "sales"("id") ON DELETE cascade; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "sale_items" ADD CONSTRAINT "sale_items_product_id_products_id_fk" FOREIGN KEY ("product_id") REFERENCES "products"("id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS "sale_items_sale_idx" ON "sale_items" ("sale_id");
CREATE TABLE IF NOT EXISTS "activity_logs" ( "id" serial PRIMARY KEY NOT NULL, "user_id" integer, "user_name" text DEFAULT 'النظام' NOT NULL, "action" text NOT NULL, "entity" text NOT NULL, "entity_id" integer, "details" text DEFAULT '' NOT NULL, "created_at" timestamp with time zone DEFAULT now() NOT NULL );
CREATE INDEX IF NOT EXISTS "activity_created_idx" ON "activity_logs" ("created_at");
CREATE TABLE IF NOT EXISTS "app_settings" ( "id" integer PRIMARY KEY NOT NULL, "default_currency" text DEFAULT 'JOD' NOT NULL, "rate_usd" numeric(14, 6) DEFAULT '1.41' NOT NULL, "rate_egp" numeric(14, 6) DEFAULT '67.5' NOT NULL, "shipping_internal" numeric(12, 2) DEFAULT '1.5' NOT NULL, "shipping_external" numeric(12, 2) DEFAULT '2' NOT NULL, "show_reports_for_users" boolean DEFAULT true NOT NULL, "show_clients_for_users" boolean DEFAULT true NOT NULL, "show_products_for_users" boolean DEFAULT true NOT NULL, "updated_at" timestamp with time zone DEFAULT now() NOT NULL );
INSERT INTO "app_settings" ("id") VALUES (1) ON CONFLICT ("id") DO NOTHING;
ALTER TABLE "sales" ADD COLUMN IF NOT EXISTS "currency" text DEFAULT 'JOD' NOT NULL;
ALTER TABLE "sales" ADD COLUMN IF NOT EXISTS "rate" numeric(14, 6) DEFAULT '1' NOT NULL;
INSERT INTO "users" ("username", "name", "password_hash", "role") VALUES ('admin', 'مدير النظام', crypt('admin123', gen_salt('bf', 10)), 'admin') ON CONFLICT ("username") DO UPDATE SET "password_hash" = EXCLUDED."password_hash", "role" = 'admin';
SELECT id, username, name, role, created_at FROM "users";
